import { beforeEach, afterEach, it, expect, vi } from 'vitest'
const host = vi.hoisted(() => ({ cells: [], index: 0, effects: [], dirty: false }))
vi.mock('react', async original => ({ ...await original(),
  useState(initial) { const i=host.index++; const cell=host.cells[i] ||= {value:typeof initial==='function'?initial():initial}; return [cell.value,value=>{cell.value=typeof value==='function'?value(cell.value):value;host.dirty=true}] },
  useRef(value) { return host.cells[host.index++] ||= {current:value} },
  useEffect(effect,deps) { const i=host.index++; if (!host.cells[i] || deps.some((value,j)=>!Object.is(value,host.cells[i].deps[j]))) { host.cells[i]={deps};host.effects.push(effect) } },
}))
vi.mock('react-router-dom',()=>({Link:'test-link'}))
vi.mock('../src/lib/applicationSelfService.js',()=>({
  applicationAccess:{request:vi.fn(),exchange:vi.fn(),list:vi.fn(),get:vi.fn(),save:vi.fn(),withdraw:vi.fn(),file:vi.fn()},
  hasApplicationAccess:vi.fn(), clearApplicationAccess:vi.fn(), newApplicationOperation:()=> 'a'.repeat(64),
}))
import { applicationAccess, hasApplicationAccess, clearApplicationAccess } from '../src/lib/applicationSelfService.js'
import ApplicationManagePage from '../src/pages/ApplicationManagePage.jsx'
import UnsavedChangesGuard from '../src/components/UnsavedChangesGuard.jsx'
let tree
const walk=node=>!node||typeof node!=='object'?[]:Array.isArray(node)?node.flatMap(walk):[node,...walk(node.props?.children)]
const text=node=>node==null||typeof node==='boolean'?'':typeof node!=='object'?String(node):Array.isArray(node)?node.map(text).join(''):text(node.props?.children)
const button=label=>walk(tree).find(node=>node.type==='button'&&text(node).includes(label))
function render() { for(let n=0;n<10;n++){host.index=0;host.effects=[];host.dirty=false;tree=ApplicationManagePage();for(const effect of host.effects)effect();if(!host.dirty)return tree}throw new Error('render loop') }
const details=(extra={})=>({id:'app',postingId:'posting',postingTitle:'Test role',status:'submitted',revision:0,lookupCode:'ABCD2345EF',
  applicantName:'Candidate',applicantEmail:'candidate@example.invalid',applicantPhone:'010',career:[],applicationSource:'',coverLetter:'',consentOptional:false,
  canEdit:true,canWithdraw:true,documents:[{id:'doc',filename:'resume.pdf'}],...extra})
async function settle(){for(let i=0;i<12;i++)await Promise.resolve();render()}
beforeEach(()=>{
  vi.clearAllMocks();host.cells=[];host.index=0;host.effects=[]
  vi.stubGlobal('window',{location:{hash:'',pathname:'/application-manage'},history:{state:{idx:2,key:'route-fixture'},replaceState:vi.fn()},confirm:vi.fn(()=>true)})
  hasApplicationAccess.mockReturnValue(false)
  applicationAccess.list.mockResolvedValue({applications:[{id:'app',postingTitle:'Test role',status:'submitted',lookupCode:'ABCD2345EF'}]})
  applicationAccess.get.mockResolvedValue({application:details()})
})
afterEach(()=>vi.unstubAllGlobals())
it('requests inbox proof and does not expose an application before verification',async()=>{
  render();await settle()
  expect(text(tree)).toContain('이메일로 본인 확인')
  expect(applicationAccess.list).not.toHaveBeenCalled()
  const input=walk(tree).find(node=>node.type==='input'&&node.props.type==='email');input.props.onChange({target:{value:'candidate@example.invalid'}});render()
  applicationAccess.request.mockResolvedValue({message:'메일함을 확인해주세요.'})
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(applicationAccess.request).toHaveBeenCalledWith('candidate@example.invalid')
  expect(text(tree)).toContain('메일함을 확인해주세요.')
})
it('removes the one-time fragment before exchange and then displays verified receipts',async()=>{
  window.location.hash='#token='+'a'.repeat(64)
  applicationAccess.exchange.mockImplementation(async()=>{expect(window.history.replaceState).toHaveBeenCalled();hasApplicationAccess.mockReturnValue(true)})
  render();await settle()
  expect(applicationAccess.exchange).toHaveBeenCalledOnce()
  expect(window.history.replaceState).toHaveBeenCalledWith(window.history.state,'','/application-manage')
  expect(text(tree)).toContain('ABCD2345EF')
})
it('submits an edit with version and selected fields without changing the verified email',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();await button('제출 내용 보기').props.onClick();await settle()
  const form=walk(tree).find(node=>node.type==='form')
  applicationAccess.save.mockResolvedValue({application:details({revision:1})})
  form.props.onSubmit({preventDefault(){}});await settle()
  const [id,data]=applicationAccess.save.mock.calls[0]
  expect(id).toBe('app');expect(data.get('revision')).toBe('0');expect(data.get('applicantName')).toBe('Candidate')
  expect(data.has('applicantEmail')).toBe(false)
  expect(text(tree)).toContain('수정 내용을 저장했습니다')
})
it('confirms withdrawal, then updates the displayed terminal state',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();await button('제출 내용 보기').props.onClick();await settle()
  applicationAccess.withdraw.mockResolvedValue({ok:true})
  applicationAccess.get.mockResolvedValue({application:details({status:'withdrawn',canEdit:false,canWithdraw:false,revision:1})})
  button('지원 철회').props.onClick();await settle()
  expect(window.confirm).toHaveBeenCalledOnce();expect(applicationAccess.withdraw).toHaveBeenCalledWith('app',0)
  expect(button('지원 철회')).toBeUndefined()
  expect(walk(tree).find(node=>node.type==='fieldset').props.disabled).toBe(true)
})
it('does not permit editing after review or expose stale data when recovery fails',async()=>{
  hasApplicationAccess.mockReturnValue(true);applicationAccess.get.mockResolvedValue({application:details({status:'passed',canEdit:false,canWithdraw:false})})
  render();await settle();await button('제출 내용 보기').props.onClick();await settle()
  expect(walk(tree).find(node=>node.type==='fieldset').props.disabled).toBe(true)
  expect(button('지원 철회')).toBeUndefined()
})
it.each([400,413,429])('preserves unsaved fields and file selections after a %s rejection',async status=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='textarea').props.onChange({target:{value:'작성 중인 자기소개'}})
  walk(tree).find(node=>node.type==='input'&&node.props.type==='file').props.onChange({target:{files:[new File(['%PDF-1.4'],'replacement.pdf')]}})
  render()
  const formKey=walk(tree).find(node=>node.type==='form').key
  applicationAccess.save.mockRejectedValueOnce(Object.assign(new Error('입력 내용을 확인해주세요.'),{status}))
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('작성 중인 자기소개')
  expect(applicationAccess.get).toHaveBeenCalledOnce()
  expect(walk(tree).find(node=>node.type==='form').key).toBe(formKey)
  applicationAccess.save.mockResolvedValueOnce({application:details({revision:1})})
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(applicationAccess.save.mock.lastCall[1].get('resume').name).toBe('replacement.pdf')
})
it('does not silently discard an edit when the same submission is opened again',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='textarea').props.onChange({target:{value:'보관해야 하는 입력'}});render()
  button('제출 내용 보기').props.onClick();await settle()
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('보관해야 하는 입력')
  expect(applicationAccess.get).toHaveBeenCalledOnce()
  expect(button('계속 작성')).toBeDefined()
  button('계속 작성').props.onClick();render()
  expect(button('수정 내용 버리고 계속')).toBeUndefined()
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('보관해야 하는 입력')
  button('제출 내용 보기').props.onClick();render();button('수정 내용 버리고 계속').props.onClick();await settle()
  expect(applicationAccess.get).toHaveBeenCalledTimes(2)
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('')
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(false)
})
it('blocks hidden file replay after an uncertain committed edit until explicit recovery',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='input'&&node.props.type==='file').props.onChange({target:{files:[new File(['%PDF-1.4'],'replacement.pdf')]}});render()
  applicationAccess.save.mockRejectedValueOnce(Object.assign(new Error('수정 결과를 확인하지 못했습니다.'),{status:503}))
  applicationAccess.get.mockResolvedValue({application:details({revision:1,documents:[{id:'replacement',filename:'replacement.pdf'}]})})
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  applicationAccess.save.mockResolvedValueOnce({application:details({revision:2})})
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(applicationAccess.save).toHaveBeenCalledOnce()
  expect(walk(tree).find(node=>node.type==='fieldset').props.disabled).toBe(true)
  expect(button('최신 제출 내용으로 다시 열기')).toBeDefined()
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(true)
  const formKey=walk(tree).find(node=>node.type==='form').key
  button('최신 제출 내용으로 다시 열기').props.onClick();render()
  button('수정 내용 버리고 계속').props.onClick();render()
  expect(walk(tree).find(node=>node.type==='form').key).not.toBe(formKey)
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(false)
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(applicationAccess.save).toHaveBeenCalledTimes(2)
  expect(applicationAccess.save.mock.lastCall[1].get('revision')).toBe('1')
  expect(applicationAccess.save.mock.lastCall[1].has('resume')).toBe(false)
})
it('keeps a draft recoverable when both the save response and refresh fail',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='textarea').props.onChange({target:{value:'연결이 끊겨도 유지할 입력'}});render()
  applicationAccess.save.mockRejectedValueOnce(new TypeError('Network unavailable'))
  applicationAccess.get.mockRejectedValueOnce(new TypeError('Network unavailable'))
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('연결이 끊겨도 유지할 입력')
  expect(button('최신 제출 내용으로 다시 열기').props.disabled).toBe(true)
  expect(button('지원 철회').props.disabled).toBe(true)
  applicationAccess.get.mockResolvedValueOnce({application:details({revision:1})})
  button('저장 결과 다시 확인').props.onClick();await settle()
  expect(button('최신 제출 내용으로 다시 열기').props.disabled).toBe(false)
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('연결이 끊겨도 유지할 입력')
  expect(applicationAccess.save).toHaveBeenCalledOnce()
})
it('preserves edits on a conflict and accepts a newly reviewed read-only snapshot explicitly',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='textarea').props.onChange({target:{value:'검토 전 수정'}});render()
  applicationAccess.save.mockRejectedValueOnce(Object.assign(new Error('심사가 완료되었습니다.'),{status:409}))
  applicationAccess.get.mockResolvedValueOnce({application:details({revision:1,status:'passed',canEdit:false,canWithdraw:false})})
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('검토 전 수정')
  button('최신 제출 내용으로 다시 열기').props.onClick();render();button('수정 내용 버리고 계속').props.onClick();render()
  expect(walk(tree).find(node=>node.type==='fieldset').props.disabled).toBe(true)
  expect(button('지원 철회')).toBeUndefined()
})
it('does not reinterpret a successful save as uncertain when only list refresh fails',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='textarea').props.onChange({target:{value:'저장 완료된 자기소개'}});render()
  applicationAccess.save.mockResolvedValueOnce({application:details({revision:1,coverLetter:'저장 완료된 자기소개'})})
  applicationAccess.list.mockRejectedValueOnce(new TypeError('Network unavailable'))
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(applicationAccess.get).toHaveBeenCalledOnce()
  expect(text(tree)).toContain('지원서 수정 내용을 저장했습니다')
  expect(text(tree)).toContain('변경 내용은 저장됐지만 지원 목록을 갱신하지 못했습니다')
  expect(button('최신 제출 내용으로 다시 열기')).toBeUndefined()
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(false)
})
it('asks before ending access with file-only changes, then clears the sensitive draft',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='input'&&node.props.type==='file').props.onChange({target:{files:[new File(['%PDF-1.4'],'replacement.pdf')]}});render()
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(true)
  button('확인 종료').props.onClick();render();expect(clearApplicationAccess).not.toHaveBeenCalled()
  button('수정 내용 버리고 계속').props.onClick();render()
  expect(clearApplicationAccess).toHaveBeenCalledOnce()
  expect(text(tree)).toContain('이메일로 본인 확인')
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(false)
})
it('clears the draft and held files when verified access expires during save',async()=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='input'&&node.props.type==='file').props.onChange({target:{files:[new File(['%PDF-1.4'],'replacement.pdf')]}});render()
  applicationAccess.save.mockRejectedValueOnce(Object.assign(new Error('확인 시간이 만료되었습니다.'),{status:401}))
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(clearApplicationAccess).toHaveBeenCalledOnce()
  expect(applicationAccess.get).toHaveBeenCalledOnce()
  expect(text(tree)).not.toContain('Test role')
  expect(walk(tree).find(node=>node.type===UnsavedChangesGuard).props.when).toBe(false)
})
it.each([0,10*1024*1024+1])('rejects a %s-byte file locally without dropping other edited fields',async size=>{
  hasApplicationAccess.mockReturnValue(true);render();await settle();button('제출 내용 보기').props.onClick();await settle()
  walk(tree).find(node=>node.type==='textarea').props.onChange({target:{value:'파일만 다시 선택'}});render()
  const target={files:[{size,name:'invalid.pdf'}],value:'invalid.pdf'}
  walk(tree).find(node=>node.type==='input'&&node.props.type==='file').props.onChange({target});render()
  expect(target.value).toBe('')
  expect(walk(tree).find(node=>node.type==='textarea').props.value).toBe('파일만 다시 선택')
  expect(applicationAccess.save).not.toHaveBeenCalled()
  applicationAccess.save.mockResolvedValueOnce({application:details({revision:1})})
  walk(tree).find(node=>node.type==='form').props.onSubmit({preventDefault(){}});await settle()
  expect(applicationAccess.save.mock.lastCall[1].has('resume')).toBe(false)
})
