CREATE TABLE contract_terms (
  room_id TEXT PRIMARY KEY REFERENCES interview_rooms(id),
  employer_name TEXT,
  employer_address TEXT,
  employee_name TEXT,
  employee_address TEXT,
  contract_start_date TEXT,
  contract_end_date TEXT,
  work_location TEXT,
  job_description TEXT,
  work_hours_start TEXT,
  work_hours_end TEXT,
  work_days TEXT,
  rest_days TEXT,
  wage_base_amount INTEGER,
  wage_pay_method TEXT,
  wage_pay_date TEXT,
  annual_leave TEXT,
  social_insurance_json TEXT,
  uniform_size TEXT,
  custom_terms_json TEXT,
  hire_confirmed INTEGER NOT NULL DEFAULT 0,
  hire_confirmed_at TEXT,
  hire_confirmation_excerpt TEXT,
  extraction_confidence REAL,
  last_analyzed_message_id INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
