-- Generated from migrations/*.sql by scripts/build-supabase-migration.mjs.
-- Business columns intentionally stay TEXT/INTEGER compatible with the existing API.
BEGIN;

CREATE OR REPLACE FUNCTION public.datetime()
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS');
$$;

CREATE OR REPLACE FUNCTION public.datetime(value TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT to_char(
    timezone('utc', CASE WHEN value IS NULL OR lower(value) = 'now' THEN now() ELSE value::timestamptz END),
    'YYYY-MM-DD HH24:MI:SS'
  );
$$;

CREATE OR REPLACE FUNCTION public.datetime(value TEXT, modifier TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT to_char(
    timezone(
      'utc',
      (CASE WHEN value IS NULL OR lower(value) = 'now' THEN now() ELSE value::timestamptz END)
        + COALESCE(NULLIF(modifier, ''), '0 seconds')::interval
    ),
    'YYYY-MM-DD HH24:MI:SS'
  );
$$;

CREATE OR REPLACE FUNCTION public.datetime(value TEXT, modifier_one TEXT, modifier_two TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT to_char(
    timezone(
      'utc',
      (CASE WHEN value IS NULL OR lower(value) = 'now' THEN now() ELSE value::timestamptz END)
        + COALESCE(NULLIF(modifier_one, ''), '0 seconds')::interval
        + COALESCE(NULLIF(modifier_two, ''), '0 seconds')::interval
    ),
    'YYYY-MM-DD HH24:MI:SS'
  );
$$;

CREATE OR REPLACE FUNCTION public.date(value TEXT, modifier TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT to_char(
    timezone(
      'utc',
      (CASE WHEN value IS NULL OR lower(value) = 'now' THEN now() ELSE value::timestamptz END)
        + COALESCE(NULLIF(modifier, ''), '0 seconds')::interval
    ),
    'YYYY-MM-DD'
  );
$$;

CREATE OR REPLACE FUNCTION public.julianday(value TEXT)
RETURNS DOUBLE PRECISION
LANGUAGE SQL
STABLE
AS $$
  SELECT extract(epoch FROM value::timestamptz) / 86400.0 + 2440587.5;
$$;

CREATE OR REPLACE FUNCTION public.json_array_length(value TEXT)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT jsonb_array_length(COALESCE(NULLIF(value, ''), '[]')::jsonb);
$$;

-- 0001_init.sql
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('company','candidate')),
  display_name TEXT NOT NULL,
  company_name TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE sessions (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);

-- 0002_rooms.sql
CREATE TABLE interview_rooms (
  id TEXT PRIMARY KEY,
  company_user_id TEXT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','active','contract_pending','signed','closed')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  closed_at TEXT
);

CREATE TABLE room_participants (
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  role_in_room TEXT NOT NULL CHECK (role_in_room IN ('company','candidate')),
  joined_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (room_id, user_id)
);

-- 0003_chat.sql
CREATE TABLE chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  sender_user_id TEXT NOT NULL REFERENCES users(id),
  body TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_chat_messages_room ON chat_messages(room_id, id);

-- 0004_documents.sql
CREATE TABLE documents (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  doc_type TEXT NOT NULL CHECK (doc_type IN ('resume', 'cover_letter')),
  filename TEXT NOT NULL,
  r2_key TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  content_type TEXT NOT NULL,
  uploaded_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(user_id, doc_type)
);

-- 0005_contract_terms.sql
CREATE TABLE contract_terms (
  room_id TEXT PRIMARY KEY REFERENCES interview_rooms(id),
  employer_name TEXT,
  employer_address TEXT,
  employee_name TEXT,
  employee_address TEXT,
  contract_start_date TEXT,
  contract_end_date TEXT,
  work_location TEXT,
  job_description TEXT,
  work_hours_start TEXT,
  work_hours_end TEXT,
  work_days TEXT,
  rest_days TEXT,
  wage_base_amount INTEGER,
  wage_pay_method TEXT,
  wage_pay_date TEXT,
  annual_leave TEXT,
  social_insurance_json TEXT,
  uniform_size TEXT,
  custom_terms_json TEXT,
  hire_confirmed INTEGER NOT NULL DEFAULT 0,
  hire_confirmed_at TEXT,
  hire_confirmation_excerpt TEXT,
  extraction_confidence REAL,
  last_analyzed_message_id INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 0006_signatures.sql
CREATE TABLE signatures (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  signer_user_id TEXT NOT NULL REFERENCES users(id),
  signer_role TEXT NOT NULL CHECK (signer_role IN ('company','candidate')),
  image_data_url TEXT NOT NULL,
  signed_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(room_id, signer_role)
);

-- 0007_room_participants_one_candidate.sql
CREATE UNIQUE INDEX idx_room_participants_one_candidate
  ON room_participants(room_id)
  WHERE role_in_room = 'candidate';

-- 0008_contract_terms_last_analyzed.sql
ALTER TABLE contract_terms ADD COLUMN last_analyzed_at TEXT;

-- 0009_rate_limit_hits.sql
CREATE TABLE rate_limit_hits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_rate_limit_hits_bucket ON rate_limit_hits(bucket, created_at);

-- 0010_admin.sql
ALTER TABLE users ADD COLUMN is_admin INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN is_suspended INTEGER NOT NULL DEFAULT 0;

-- 0011_contract_ai_document.sql
ALTER TABLE contract_terms ADD COLUMN ai_document_json TEXT;

-- 0012_recruiter.sql
ALTER TABLE users ADD COLUMN is_recruiter INTEGER NOT NULL DEFAULT 0;

-- 0013_must_change_password.sql
ALTER TABLE users ADD COLUMN must_change_password INTEGER NOT NULL DEFAULT 0;

-- 0014_admin_audit_log.sql
CREATE TABLE admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id TEXT NOT NULL REFERENCES users(id),
  action TEXT NOT NULL,
  target_user_id TEXT REFERENCES users(id),
  target_room_id TEXT REFERENCES interview_rooms(id),
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_admin_audit_log_created_at ON admin_audit_log(created_at);

-- 0015_contract_edit_history.sql
CREATE TABLE contract_edit_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  editor_user_id TEXT NOT NULL REFERENCES users(id),
  changes TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_contract_edit_history_room ON contract_edit_history(room_id, id);

-- 0016_final_offer_emails.sql
CREATE TABLE final_offer_emails (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL UNIQUE REFERENCES interview_rooms(id),
  sent_by_user_id TEXT NOT NULL REFERENCES users(id),
  recipient_email TEXT NOT NULL,
  subject TEXT NOT NULL,
  body_text TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('sending', 'sent', 'failed')),
  attempt_count INTEGER NOT NULL DEFAULT 1,
  error_message TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  sent_at TEXT
);

CREATE INDEX idx_final_offer_emails_status ON final_offer_emails(status);

-- 0017_job_applications.sql
-- 채용 공고 + 공개 지원 시스템

-- 채용 공고 (채용자/관리자가 등록)
CREATE TABLE job_postings (
  id TEXT PRIMARY KEY,
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  department TEXT,          -- 부서/조직 (예: Enterprise)
  employment_type TEXT,     -- 고용형태 (정규직/인턴/계약직 등)
  location TEXT,            -- 근무지
  description TEXT NOT NULL, -- 상세 설명
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_job_postings_status ON job_postings(status, created_at);
CREATE INDEX idx_job_postings_creator ON job_postings(created_by_user_id);

-- 공개 지원서 (로그인 없이 이메일을 식별자로 제출)
CREATE TABLE applications (
  id TEXT PRIMARY KEY,
  posting_id TEXT NOT NULL REFERENCES job_postings(id),
  applicant_name TEXT NOT NULL,
  applicant_email TEXT NOT NULL,
  applicant_phone TEXT NOT NULL,
  career_json TEXT,           -- 경력사항 (JSON 배열)
  application_source TEXT,     -- 지원 경로
  cover_letter TEXT,           -- 자기소개/지원동기 (선택)
  -- 개인정보 수집·이용 동의
  consent_required INTEGER NOT NULL DEFAULT 0,    -- 필수항목 (반드시 1)
  consent_optional INTEGER NOT NULL DEFAULT 0,    -- 선택항목
  consent_third_party INTEGER NOT NULL DEFAULT 0, -- 제3자 제공
  consented_at TEXT,
  -- 심사 상태
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'passed', 'rejected')),
  created_user_id TEXT REFERENCES users(id),    -- 서류합격 시 생성된 계정
  room_id TEXT REFERENCES interview_rooms(id),  -- 서류합격 시 생성된 면접방
  reviewed_by_user_id TEXT REFERENCES users(id),
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_applications_posting ON applications(posting_id, created_at);
CREATE INDEX idx_applications_status ON applications(status);
CREATE INDEX idx_applications_email ON applications(applicant_email);

-- 지원서 첨부파일 (R2 저장, 지원서 id로 연결)
CREATE TABLE application_documents (
  id TEXT PRIMARY KEY,
  application_id TEXT NOT NULL REFERENCES applications(id),
  doc_type TEXT NOT NULL CHECK (doc_type IN ('resume', 'portfolio')),
  filename TEXT NOT NULL,
  r2_key TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  content_type TEXT NOT NULL,
  uploaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_application_documents_app ON application_documents(application_id);

-- 0018_signed_contracts.sql
-- 서명 완료된 근로계약서 보관(R2) + 지원자 이메일 발송 기록

CREATE TABLE signed_contracts (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL UNIQUE REFERENCES interview_rooms(id),
  r2_key TEXT NOT NULL,
  filename TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  stored_by_user_id TEXT NOT NULL REFERENCES users(id),
  email_status TEXT NOT NULL DEFAULT 'not_sent' CHECK (email_status IN ('not_sent', 'sent', 'failed')),
  email_error TEXT,
  emailed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 0019_applications_unique_submitted.sql
-- 같은 공고에 같은 이메일로 '심사 대기(submitted)' 지원이 중복 생성되는 것을
-- DB 차원에서 방지 (동시 제출 경쟁조건 방어). 불합격/합격 후에는 재지원 가능하도록
-- status='submitted' 인 행에만 적용하는 부분 유니크 인덱스.
CREATE UNIQUE INDEX idx_applications_one_submitted
  ON applications(posting_id, applicant_email)
  WHERE status = 'submitted';

-- 0020_job_posting_deadline.sql
-- 채용 공고 마감일 (YYYY-MM-DD, nullable = 상시 모집).
-- 공개 목록/상세/지원에서 마감일이 지난 공고는 자동으로 노출·접수 중단.
ALTER TABLE job_postings ADD COLUMN deadline TEXT;

-- 0021_developer.sql
-- 개발자(developer) 권한: 관리자 위의 최상위 등급.
-- 관리자 계정을 정지/삭제/비밀번호 재설정할 수 있는 유일한 등급.
-- 개발자 계정 자체는 API로는 누구도 변경/삭제할 수 없다(DB 직접 조작 전용).
ALTER TABLE users ADD COLUMN is_developer INTEGER NOT NULL DEFAULT 0;

-- 0022_warnings_and_hash.sql
-- AI 법적 검토 경고(분석 시 저장) + 서명 계약서 위변조 방지 해시
ALTER TABLE contract_terms ADD COLUMN analysis_warnings_json TEXT;
ALTER TABLE signed_contracts ADD COLUMN sha256_hash TEXT;

-- 0023_screening_notifications_lookup.sql
-- 지원서 AI 스크리닝 결과 + 지원 현황 조회 코드 + 인앱 알림 센터

ALTER TABLE applications ADD COLUMN ai_screening_json TEXT;
ALTER TABLE applications ADD COLUMN screened_at TEXT;
ALTER TABLE applications ADD COLUMN lookup_code TEXT;
CREATE UNIQUE INDEX idx_applications_lookup_code ON applications(lookup_code) WHERE lookup_code IS NOT NULL;

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_notifications_user ON notifications(user_id, id);

-- 0024_performance_indexes.sql
-- 조회 패턴에 맞는 인덱스 보강.
--
-- room_participants의 기본키는 (room_id, user_id)라 user_id만으로 조회할 때는
-- 인덱스를 탈 수 없다. 그런데 "내 면접방 목록"과 "문서 열람 권한 확인"은
-- 모두 user_id로만 찾기 때문에 매번 전체 스캔이 발생한다.
CREATE INDEX idx_room_participants_user ON room_participants(user_id);

-- 계정 정지·비밀번호 재설정·삭제 시 해당 사용자의 세션을 모두 지운다.
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- 면접방 생성자 기준 조회(알림 대상 확인 등).
CREATE INDEX idx_interview_rooms_company ON interview_rooms(company_user_id);

-- 0025_contract_change_requests.sql
-- 계약 조건 수정 요청.
--
-- 지금까지 계약서는 회사만 쓰고 지원자는 읽거나 서명만 할 수 있었다.
-- 서명 전 점검이 "합의와 다르다"고 알려줘도 지원자가 할 수 있는 일이 없어,
-- 문제를 짚어주고 해결 경로는 없는 반쪽짜리 흐름이었다.
-- 지원자가 항목별로 수정을 요청하고 회사가 수락·거절하도록 한다.
CREATE TABLE contract_change_requests (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  requested_by_user_id TEXT NOT NULL REFERENCES users(id),
  field TEXT NOT NULL,
  current_value TEXT,
  requested_value TEXT NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  response_note TEXT,
  responded_by_user_id TEXT REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  resolved_at TEXT
);
CREATE INDEX idx_change_requests_room ON contract_change_requests(room_id, id);

-- 0026_edit_history_source.sql
-- 계약 조건이 "어떻게" 바뀌었는지 구분한다.
--
-- 회사가 일방적으로 고친 것과, 지원자가 요청해 회사가 수락한 것은 성격이 다르다.
-- 후자는 양측이 합의한 변경이므로 서명 전 점검에서 "합의와 다름"으로 경고하면
-- 안 된다. 오히려 그 값이 새로운 합의 기준이 된다.
ALTER TABLE contract_edit_history ADD COLUMN source TEXT NOT NULL DEFAULT 'manual';

-- 0027_signature_evidence.sql
-- 서명 증거 정보.
--
-- 지금 서명은 그림 한 장일 뿐이라 "누가 언제" 이상을 증명하지 못한다.
-- 실제 전자계약 서비스의 감사추적증명서는 서명이 이루어진 접속 환경(IP·기기)을
-- 함께 기록해 사후 분쟁에서 증거로 쓴다. 같은 수준의 기록을 남긴다.
ALTER TABLE signatures ADD COLUMN signer_ip TEXT;
ALTER TABLE signatures ADD COLUMN signer_user_agent TEXT;
ALTER TABLE signatures ADD COLUMN signer_country TEXT;

-- 0028_contract_translations.sql
-- 외국인 근로자용 계약서 번역본.
--
-- 국내 외국인 근로자가 읽지 못하는 한국어 계약서에 서명하는 일은 실제로 흔하고,
-- 고용노동부 표준근로계약서에도 공식 외국어본이 존재한다. 계약 내용을 이미
-- 구조화해 갖고 있으므로, 같은 내용을 근로자의 언어로 함께 보여준다.
--
-- 원본(한국어)은 그대로 두고 번역본을 따로 보관한다. 법적 효력은 원본에 있고
-- 번역본은 이해를 돕기 위한 것임을 화면과 문서에 명시한다.
CREATE TABLE contract_translations (
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  language TEXT NOT NULL,
  articles_json TEXT NOT NULL,
  translated_by_user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (room_id, language)
);

-- 0029_contract_renewal.sql
-- 갱신 계약을 이전 계약과 연결한다.
--
-- 기간제법 제4조의 2년 상한은 "하나의 계약"이 아니라 계속근로기간으로 따진다.
-- 그런데 지금까지는 계약 하나만 보고 2년 초과를 판정했기 때문에, 1년짜리
-- 계약을 세 번 갱신해 3년을 일한 근로자는 아무 경고 없이 지나갔다. 실제로
-- 문제가 되는 것은 이 반복 갱신 쪽이다.
--
-- 계약(면접방)끼리 앞뒤를 이어 두면 계속근로기간을 합산해 판정할 수 있다.
ALTER TABLE contract_terms ADD COLUMN previous_room_id TEXT REFERENCES interview_rooms(id);

CREATE INDEX idx_contract_terms_previous ON contract_terms(previous_room_id);

-- 0030_interview_summaries.sql
-- 면접 대화의 회사 보관용 요약 기록.
--
-- 이 서비스의 축은 "대화 → 계약서"인데, 그동안 대화에서 뽑아낸 것은 계약
-- 조건뿐이었다. 무슨 이야기가 오갔는지, 무엇이 아직 정해지지 않았는지는
-- 채팅 원문을 처음부터 다시 읽어야만 알 수 있었다.
--
-- 요약은 평가서가 아니라 기록이다. 지원자를 점수로 매기지 않고, 직무와
-- 무관한 개인정보(연령·성별·출신지역·혼인관계 등)는 담지 않는다.
-- 채용절차의 공정화에 관한 법률 제4조의3의 취지에 따른 것이다.
CREATE TABLE interview_summaries (
  room_id TEXT PRIMARY KEY REFERENCES interview_rooms(id),
  summary_json TEXT NOT NULL,
  message_count INTEGER NOT NULL DEFAULT 0,
  last_message_id INTEGER,
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 0031_email_case.sql
-- 대소문자만 다른 계정이 생기지 않게 한다.
--
-- users.email의 UNIQUE는 대소문자를 구분하는데, 공개 지원 폼은 이메일을 항상
-- 소문자로 저장한다. 그래서 이메일에 대문자가 한 글자만 있어도 같은 사람이 두
-- 계정으로 갈라졌다 — 서류합격 처리가 기존 계정을 못 찾아 새 계정을 만들고,
-- 원래 계정으로 로그인한 지원자는 자기 면접방에서 403으로 막혔다. 반대로
-- 대소문자만 바꿔 가입하면 남이 낸 지원 내역과 접수번호가 "내 지원 현황"에
-- 그대로 보였다.
--
-- 애플리케이션이 저장·조회 전에 소문자로 통일하도록 고쳤고, 여기서 DB 차원의
-- 제약을 더해 우회 경로를 남기지 않는다.

-- 기존 행을 같은 규칙으로 정리한다 (이미 소문자면 바뀌는 것이 없다).
UPDATE users SET email = LOWER(TRIM(email)) WHERE email <> LOWER(TRIM(email));

-- 이제부터는 표기가 달라도 같은 이메일로 두 계정을 만들 수 없다.
CREATE UNIQUE INDEX idx_users_email_lower ON users(LOWER(email));

-- 0032_signature_revocations.sql
-- 서명 후 계약 내용이 바뀌면 기존 서명을 무효화한다.
--
-- 지금까지 계약 내용을 잠그는 조건은 interview_rooms.status = 'signed' 하나였고,
-- 그 상태는 양측이 모두 서명한 뒤에야 붙었다. 그래서 지원자가 먼저 서명한
-- 상태에서 회사가 기본급과 계약서 본문을 바꾸고 이어서 서명하면, 지원자가 본
-- 적도 없는 조건에 지원자 서명이 붙은 계약이 만들어졌다.
--
-- 증거가 약한 문제가 아니라 서로 합의한 내용이 없는 문제다. 내용이 바뀌면
-- 그 전에 받은 서명은 더 이상 그 내용에 대한 동의가 아니므로 무효로 옮기고,
-- 상대방에게 다시 서명을 받아야 한다. 무효화된 서명도 지우지 않고 남겨,
-- 무엇이 언제 왜 무효가 되었는지 계약 이력으로 증명할 수 있게 한다.
CREATE TABLE signature_revocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  signer_role TEXT NOT NULL,
  signer_user_id TEXT REFERENCES users(id),
  signed_at TEXT,
  signer_ip TEXT,
  signer_user_agent TEXT,
  signer_country TEXT,
  revoked_at TEXT NOT NULL DEFAULT (datetime('now')),
  revoked_by_user_id TEXT REFERENCES users(id),
  reason TEXT NOT NULL
);

CREATE INDEX idx_signature_revocations_room ON signature_revocations(room_id, id);

-- 0033_signature_document_hash.sql
-- 서명을 서명 대상 문서에 묶는다.
--
-- 전자서명이 "이 문서에 서명했다"를 뜻하려면 서명과 문서가 연결돼 있어야 한다.
-- 그런데 signatures 에는 서명 그림과 접속 흔적(IP·기기·국가)만 있고 어떤 내용에
-- 붙었는지가 없었다. 다툼이 생겨 "나는 그 조건에 동의하지 않았다"는 주장이
-- 나오면, 서명 데이터만으로는 무엇에 동의한 것인지 특정할 수 없었다.
--
-- 존재하는 유일한 지문은 서명이 다 끝난 뒤 회사가 올린 PDF 바이트에 대한
-- signed_contracts.sha256_hash 인데, 서명 행과 연결되지 않고 시점도 늦고
-- 회사가 버튼을 눌러야 생긴다.
--
-- 서명하는 순간 계약 내용의 지문을 계산해 서명과 함께 남긴다.
ALTER TABLE signatures ADD COLUMN document_sha256 TEXT;

-- 무효화된 서명에도 무엇에 붙어 있었는지를 남긴다.
ALTER TABLE signature_revocations ADD COLUMN document_sha256 TEXT;

-- 0034_contract_deliveries.sql
-- 근로계약서 교부 이력.
--
-- 근로기준법 제17조 제2항은 사용자가 근로계약서를 근로자에게 교부하도록 하고,
-- 위반은 제114조 벌금 대상이다. 그런데 이 앱에서 교부는 회사가 계약서 화면에서
-- 버튼을 한 번 누르는 데 달려 있었다. 누르지 않으면 계약은 'signed'로 끝나지만
-- 교부물이 아예 없고, 근로자에게 가는 것은 "계약서를 확인해보세요"라는 인앱
-- 알림 하나뿐이었다.
--
-- 받은 기록도 없었다. signed_contracts 에는 수신자 컬럼이 없고(최종합격 이메일
-- 표에는 recipient_email 이 있는데 계약서 쪽에만 없다) 다운로드 로그도 남지
-- 않아, 전자문서법 제5조가 요구하는 수신자·수신일시 보존이 함께 깨졌다.
--
-- 교부를 별도 표로 분리한 이유: PDF를 다시 저장하면 signed_contracts 의
-- emailed_at 이 NULL 로 리셋되어 교부 이력이 지워졌다. 교부는 한 번 일어난
-- 사실이므로 문서 저장과 생애주기를 분리한다.
CREATE TABLE contract_deliveries (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  recipient_user_id TEXT REFERENCES users(id),
  -- in_app: 체결 즉시 서버가 만드는 열람 가능 상태
  -- email: 이메일 발송
  -- download: 근로자가 직접 내려받음
  -- paper: 전자 수신을 원하지 않는 근로자에게 인쇄해 교부
  channel TEXT NOT NULL CHECK (channel IN ('in_app', 'email', 'download', 'paper')),
  recipient_address TEXT,
  status TEXT NOT NULL DEFAULT 'delivered',
  error_message TEXT,
  attempt_count INTEGER NOT NULL DEFAULT 1,
  delivered_at TEXT NOT NULL DEFAULT (datetime('now')),
  first_viewed_at TEXT,
  downloaded_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_contract_deliveries_room ON contract_deliveries(room_id, id);
-- 채널마다 한 행만 두어, 같은 채널의 교부가 중복으로 쌓이지 않게 한다.
CREATE UNIQUE INDEX idx_contract_deliveries_room_channel
  ON contract_deliveries(room_id, channel);

-- 0035_posting_conditions.sql
-- 채용 공고에 근로조건을 구조화해 적는다.
--
-- 지금까지 공고에 담긴 근로조건은 description 자유 텍스트뿐이었다. 그래서
-- 공고를 보고 지원한 사람이 나중에 계약서를 받았을 때, 조건이 공고와 같은지
-- 확인할 방법이 없었다. "월 250만원"이라고 적힌 공고를 보고 지원했는데 계약서에
-- 220만원이 적혀 있어도 앱은 아무것도 알려주지 않았다.
--
-- 채용절차의 공정화에 관한 법률 제4조 제3항은 구인자가 채용광고에서 제시한
-- 근로조건을 구직자에게 불리하게 변경하는 것을 금지한다. 비교할 값이 없으면
-- 그 위반을 알아차릴 수 없다.
--
-- 임금은 표기 방식이 갈리므로 종류를 함께 받는다. 범위로 제시하는 공고가 많아
-- 하한·상한을 나눠 둔다. 하한만 있으면 그것을 약속한 최소로 본다.
ALTER TABLE job_postings ADD COLUMN wage_type TEXT
  CHECK (wage_type IS NULL OR wage_type IN ('monthly', 'hourly', 'annual'));
ALTER TABLE job_postings ADD COLUMN wage_min INTEGER;
ALTER TABLE job_postings ADD COLUMN wage_max INTEGER;
ALTER TABLE job_postings ADD COLUMN work_hours_start TEXT;
ALTER TABLE job_postings ADD COLUMN work_hours_end TEXT;
ALTER TABLE job_postings ADD COLUMN work_days TEXT;

-- 0036_signature_session.sql
-- 서명을 "인증된 세션과 계정"에 묶는다.
--
-- 0027이 서명 환경(IP·기기·국가)을, 0033이 서명 대상 문서의 지문을 남기게 했지만,
-- 그 서명이 어느 계정으로 어느 로그인 세션에서 이루어졌는지는 어디에도 없었다.
-- 다툼에서 "내가 서명하지 않았다"는 주장이 나오면 접속 환경만으로는 부족하다.
--
-- 소급해 채우지 않는다. 도입 전 서명은 NULL로 남고, 증명서에는 "기록 없음
-- (도입 전 서명)"으로 정직하게 표기한다. 없는 근거를 있는 것처럼 만들지 않는다.
ALTER TABLE signatures ADD COLUMN verified_email TEXT;
ALTER TABLE signatures ADD COLUMN session_started_at TEXT;
-- 'account_password'  : 본인이 정한 비밀번호로 로그인한 세션
-- 'temp_password'     : 관리자가 발급한 임시 비밀번호를 아직 바꾸지 않은 계정
ALTER TABLE signatures ADD COLUMN verification_method TEXT;

-- 0037_audit_certificates.sql
-- 감사추적증명서 발급 이력.
--
-- 지금까지 이 앱이 내보내는 유일한 문서는 계약서 화면을 이미지로 찍어 만든
-- PDF였고, 그 이미지 바이트의 해시를 "문서 무결성 지문"으로 보여 주었다.
-- 래스터 바이트는 기기 픽셀 비율·폰트 대체에 따라 달라지므로 재현할 수 없고,
-- 재현할 수 없는 지문은 무결성을 증명하지 못한다. 정작 재현 가능한 정본 지문
-- (0033의 signatures.document_sha256)은 아무 데로도 내보내지지 않았다.
--
-- 증명서를 발급 시점에 동결해 보관한다. 이후 계약 내용이 바뀌어도 발급된
-- 증명서는 그대로 검증된다.
--
-- canonical_text를 함께 보관하는 이유: 검증을 "저장된 원본 문자열을 다시
-- 해시해 대조"로 하면, 나중에 직렬화 규칙을 바꿔도 옛 증명서가 변조로
-- 뒤집히지 않는다.
CREATE TABLE audit_certificates (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  serial TEXT NOT NULL UNIQUE,
  issued_by_user_id TEXT REFERENCES users(id),
  issued_at TEXT NOT NULL,
  document_sha256 TEXT,
  certificate_sha256 TEXT NOT NULL,
  canonical_text TEXT NOT NULL,
  snapshot_json TEXT NOT NULL,
  event_count INTEGER NOT NULL DEFAULT 0,
  revoked_at TEXT
);

CREATE INDEX idx_audit_certificates_room ON audit_certificates(room_id, issued_at DESC);

-- 0038_employment_end.sql
-- 근로관계가 실제로 끝난 날을 기록한다.
--
-- 근로기준법 제42조의 3년 보존 기간은 시행령 제22조 제2항에 따라 "근로관계가
-- 끝난 날"부터 센다. 그런데 이 앱에는 그 날짜를 담을 자리가 없어, 계약 종료일이
-- 없는 무기계약은 서명일을 기산일로 쓰고 있었다. 재직 중인 근로자의 계약서가
-- 서명 3년 뒤 "보존 종료"로 표시되는, 방향이 정확히 반대인 오류였다.
--
-- 소급해 채우지 않는다. 기록이 없으면 "아직 끝나지 않았다"로 보는 것이 안전한
-- 쪽이고, 실제로도 대부분 그렇다.
ALTER TABLE contract_terms ADD COLUMN employment_ended_at TEXT;
ALTER TABLE contract_terms ADD COLUMN employment_end_reason TEXT;
ALTER TABLE contract_terms ADD COLUMN employment_end_recorded_at TEXT;
ALTER TABLE contract_terms ADD COLUMN employment_end_recorded_by_user_id TEXT REFERENCES users(id);

-- 0039_applications_room_index.sql
-- 계약서 화면은 열릴 때마다 "이 방이 어느 공고에서 왔는가"를 묻는다.
--
--   SELECT ... FROM applications a JOIN job_postings p ON p.id = a.posting_id
--    WHERE a.room_id = ? LIMIT 1
--
-- 채용절차법 제4조 제3항 대조(공고에 제시한 조건보다 불리해졌는지)가 이 조회
-- 하나에 달려 있어서, 계약서를 열 때마다 반드시 실행된다. 그런데 applications
-- 에는 room_id 인덱스가 없어 매번 표 전체를 훑었다. 방 단위로 조회되는 다른
-- 표(chat_messages, contract_deliveries, signature_revocations, audit_certificates,
-- contract_change_requests, contract_edit_history)는 모두 인덱스나 UNIQUE 제약을
-- 갖고 있는데 여기만 빠져 있었다.
--
-- 지원서가 쌓일수록 계약서 화면이 느려지는 종류의 문제라, 지금은 티가 나지 않는다.
CREATE INDEX IF NOT EXISTS idx_applications_room ON applications(room_id);

-- 0040_wage_items.sql
-- 임금을 구성항목으로 나눠 담는다.
--
-- 지금까지 임금은 기본급 하나였다. 실제 계약서에는 그 밑에 식대·교통비·
-- 직책수당·고정연장수당이 붙고, 근로기준법 제17조가 요구하는 것도 "임금"이
-- 아니라 임금의 구성항목·계산방법·지급방법이다.
--
-- 나누지 않으면 최저임금 판정이 양쪽으로 틀린다. 기본급 190만 + 식대 20만은
-- 최저임금 기준 210만인데 기본급만 보면 없는 위반을 만들고, 기본급 180만 +
-- 고정연장수당 40만은 합계 220만이지만 가산수당은 산입되지 않아 합계만 보면
-- 진짜 위반을 통과시킨다 (최저임금법 제6조 제4항).
--
-- 기존 계약은 소급해 채우지 않는다. 항목이 비어 있으면 기본급 하나로 취급해
-- 예전과 똑같이 계산한다.
ALTER TABLE contract_terms ADD COLUMN wage_items_json TEXT;

-- 0041_room_close_reason.sql
-- 전형을 왜 종료했는지 남긴다.
--
-- interview_rooms 에는 처음부터 status 'closed' 와 closed_at 이 정의돼 있었지만
-- 어디서도 쓰이지 않았다. 이제 방을 닫을 수 있게 하면서, 닫은 이유를 함께 남긴다.
--
-- 이유가 없으면 지원자는 "종료됨"이라는 상태만 보게 된다. 다른 사람이 뽑혀서인지,
-- 채용 자체가 취소된 것인지, 조건이 안 맞아서인지는 지원자에게 전혀 다른 의미다.
-- 채용절차법 제10조도 구직자에게 채용 여부를 알리도록 한다.
ALTER TABLE interview_rooms ADD COLUMN close_reason TEXT;

-- 0042_previous_room_unique.sql
-- 한 계약의 갱신은 하나뿐이다.
--
-- 두 계약이 같은 계약을 이전 계약으로 삼으면 계속근로기간이 두 갈래로 갈라져
-- 어느 쪽도 사실이 아니게 된다. 기간제 2년 상한 판정이 갈라지므로, 어느 쪽을
-- 보느냐에 따라 같은 근로자가 무기계약 전환 대상이 되기도 하고 아니기도 한다.
--
-- 코드에서는 SELECT 로 확인한 뒤 INSERT 하고 있었다. D1 에는 트랜잭션이 없어
-- 두 요청이 동시에 오면 둘 다 "아직 없다"를 보고 둘 다 쓴다. 확인을 DB 에
-- 맡긴다.
--
-- NULL 은 여럿이어도 된다 — 이전 계약이 없는 방이 대부분이다.
CREATE UNIQUE INDEX idx_contract_terms_previous_unique
  ON contract_terms(previous_room_id)
  WHERE previous_room_id IS NOT NULL;

-- 0043_translation_source.sql
-- 번역본이 어느 내용을 옮긴 것인지 남긴다.
--
-- 번역은 한 번 만들면 그대로 남아 있었다. 그 뒤 회사가 임금이나 근무시간을
-- 고쳐도 저장된 번역본은 바뀌지 않고, 화면은 그것을 지금 계약서의 번역본처럼
-- 보여 준다. 한국어를 읽지 못하는 근로자는 옛 조건을 읽고 서명한다 — 이 앱이
-- 서명마다 문서 지문을 묶어 두는 이유와 정확히 같은 문제다.
--
-- 번역한 시점의 문서 지문을 함께 남겨, 지금 내용과 다르면 다르다고 말한다.
-- 기존 번역본은 지문이 없으므로 '확인할 수 없음'으로 다룬다 — 없는 지문을
-- 지금 내용으로 채워 넣으면 옛 번역본이 최신인 것처럼 둔갑한다.
ALTER TABLE contract_translations ADD COLUMN source_sha256 TEXT;

-- 0044_room_lifecycle_log.sql
-- 전형 종료와 근로관계 종료가 감사추적에 남지 않았다.
--
-- 두 사건 모두 상태 컬럼(closed_at·close_reason, employment_ended_on)에만
-- 적히고, 취소하면 그 컬럼이 NULL 로 지워진다. 그러면 "종료했다가 되돌렸다"는
-- 사실이 흔적 없이 사라진다.
--
-- 이것이 왜 무거운가.
--
--   전형 종료는 채용절차법 제10조가 알리도록 한 '채용 여부 고지'의 실행이다.
--   언제 끝났다고 알렸는지가 남지 않으면 알린 사실 자체를 증명할 수 없다.
--
--   근로관계 종료일은 계약서 보존 기간 3년의 기산일이다(근로기준법 제42조·
--   시행령 제22조 제2항). 그 날짜를 적었다가 지우면 보존 시계가 통째로
--   되감기는데, 감사추적에는 아무 일도 없었던 것으로 보인다.
--
-- 상태에서 유도하는 대신 일어난 일을 그대로 적는다. 지워지는 값이 아니라
-- 쌓이는 기록이라야 증거가 된다.
--
-- 행위자는 사용자 id 가 아니라 그 시점의 이름으로 남긴다. 계정이 나중에
-- 삭제돼도 누가 했는지는 남아야 하고, 외래키로 묶어 두면 계정 삭제가 이
-- 표 때문에 실패한다.
CREATE TABLE room_lifecycle_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  actor_name TEXT,
  action TEXT NOT NULL,
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_room_lifecycle_room ON room_lifecycle_log(room_id);

-- 0045_translation_updated_at.sql
-- 같은 언어를 다시 번역하면 최초 번역 시각이 사라졌다.
--
-- contract_translations 는 (room_id, language) 당 한 행이고, 재번역은
-- created_at 을 현재 시각으로 덮어썼다. 감사추적의 '외국어 계약서 생성'
-- 이벤트는 이 값 하나만 보므로, 서명 전에 만들어 근로자가 읽은 번역본이
-- 이력에서는 서명 뒤에 처음 생긴 것으로 바뀐다.
--
-- 외국인 근로자가 서명 시점에 자기 언어로 계약서를 읽을 수 있었는가는
-- 다툼이 생겼을 때 핵심이 되는 사실이다. 그 사실이 정반대로 기록된다.
--
-- 처음 만든 시각은 그대로 두고, 다시 만든 시각을 따로 남긴다.
ALTER TABLE contract_translations ADD COLUMN updated_at TEXT;

-- 0046_employee_count.sql
-- 상시 근로자 수. 근로기준법의 어느 조항이 적용되는지가 여기서 갈린다.
--
-- 제11조 제1항: "이 법은 상시 5명 이상의 근로자를 사용하는 모든 사업 또는
-- 사업장에 적용한다." 제2항과 시행령 제7조 별표1에 따라, 상시 4명 이하
-- 사업장에는 제53조(연장근로 제한)·제56조(연장·야간·휴일 가산수당)·
-- 제60조(연차 유급휴가)가 적용되지 않는다. 반면 제17조(근로조건 명시)·
-- 제54조(휴게)·제55조(주휴일)·최저임금법·퇴직급여법은 그대로 적용된다.
--
-- 이 앱은 그 구분 없이 모든 계약에 세 조항을 적용해 왔다. 그래서 상시 3명인
-- 사업장의 계약이 '주 52시간 초과'로 서명을 거부당하고 — 그 조항은 적용되지
-- 않는데 — 반대로 근로자에게는 생기지 않는 연차 15일과 받을 수 없는 가산수당
-- 단가를 확정 금액으로 제시했다. 양쪽 다 틀린 말을 확신을 갖고 한 것이다.
--
-- 비워 두면 '모름'이다. 모를 때는 5명 이상으로 보아 근로자에게 유리한 쪽으로
-- 판정하되, 그 전제를 화면에 함께 밝힌다.
ALTER TABLE contract_terms ADD COLUMN employee_count INTEGER;

-- 0047_negotiation_log.sql
-- 처우 협의 이력.
--
-- 근로조건은 계약서에 적히기 전에 대화에서 먼저 정해진다. 그런데 그 과정이
-- 어디에도 남지 않았다. 계약서 수정 이력은 계약서를 고친 뒤부터의 이야기이고,
-- 그 앞에서 무엇을 제시하고 무엇을 받아들였는지는 채팅 로그 수백 줄 안에
-- 흩어져 있다.
--
-- 두 가지를 위해 남긴다.
--
--   채용내정이 성립했는지 판단하려면 "무엇을 약속했는가"가 있어야 한다.
--   조건 없이 "합격입니다"만으로는 계약 내용이 특정되지 않는다.
--
--   확정 뒤에 조건이 불리하게 바뀌었는지 따지려면 기준이 있어야 한다. 회사가
--   "원래 그렇게 말한 적 없다"고 할 때, 언제 누가 무엇을 말했는지가 필요하다.
--
-- 발화자는 이름이 아니라 역할로 남긴다. 누가 제시한 값인지가 중요하지
-- 개인을 특정할 필요는 없고, 계정이 지워져도 이력은 남아야 한다.
CREATE TABLE negotiation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  message_id INTEGER,
  speaker_role TEXT NOT NULL,
  field TEXT NOT NULL,
  label TEXT NOT NULL,
  value TEXT NOT NULL,
  value_display TEXT NOT NULL,
  previous_value TEXT,
  excerpt TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_negotiation_room ON negotiation_log(room_id, id);

-- 0048_room_archive.sql
-- 면접방 보관처리.
--
-- 전형 종료(closed)는 "이 채용은 이 사람으로 진행하지 않는다"는 결정이고,
-- 체결(signed)은 "계약이 성립했다"는 사실이다. 둘 다 그 방에서 앞으로 무슨
-- 일이 더 일어날 수 있는지를 말한다.
--
-- 보관은 다른 이야기다. 더 일어날 일이 없으니 지금 상태 그대로 잠근다는
-- 뜻이고, 그래서 상태(status)가 아니라 별도의 표시로 둔다. 종료된 방도
-- 체결된 방도 보관할 수 있어야 하는데, status 를 'archived' 로 덮으면 그
-- 방이 종료였는지 체결이었는지가 지워진다. 채용내정 성립 여부를 다투는
-- 자리에서 그 구분이 사라지는 것은 기록을 잃는 것과 같다.
--
-- 보관하면 대화도 계약서 저장도 막힌다. 잠그는 기능이라 누가 언제 잠갔는지
-- 함께 남긴다 -- 자세한 이력은 room_lifecycle_log 에 쌓이지만, 지금 잠겨
-- 있다는 사실과 그 시각은 방을 읽을 때마다 필요하다.
ALTER TABLE interview_rooms ADD COLUMN archived_at TEXT;
ALTER TABLE interview_rooms ADD COLUMN archived_by_name TEXT;

CREATE INDEX idx_rooms_archived ON interview_rooms(archived_at);

-- 0049_break_time.sql
-- 휴게시간.
--
-- 계약서 인쇄본의 소정근로시간 줄은 이렇게 찍히고 있었다.
--
--   09:00부터 18:00까지 (휴게시간 : __시 __분 ~ __시 __분)
--
-- 괄호 안이 상수로 박힌 빈칸이었다. 입력란도 없고 저장하는 칸도 없으니
-- 채울 방법 자체가 없었다. 서명하고 보관하고 지원자에게 교부되는 문서에
-- 빈칸 하나가 언제나 남는다.
--
-- 휴게시간은 적어도 되는 항목이 아니다.
--
--   근로기준법 제54조는 4시간 근로에 30분 이상, 8시간 근로에 1시간 이상의
--   휴게를 근로시간 도중에 주도록 한다.
--
--   같은 법 제17조 제1항 제5호와 시행령 제8조 제2호는 제93조 제1호의 사항을
--   근로계약에 명시하도록 하는데, 제93조 제1호가 '업무의 시작과 종료 시각,
--   휴게시간'이다. 즉 계약서에 적어야 하는 값이다.
--
-- 정본 직렬화(TERM_ORDER)에는 넣지 않는다. 줄을 하나 더하면 이미 서명된
-- 계약서의 지문이 소급해 바뀌어, 아무도 손대지 않은 계약이 '내용이 바뀜'으로
-- 뒤집힌다. 서명 직전 변경은 화면이 읽은 저장 시각(termsUpdatedAt)으로 막는다.
ALTER TABLE contract_terms ADD COLUMN break_time TEXT;

-- 0050_room_access.sql
-- 코드만으로 면접방에 들어온 사람의 접속.
--
-- 지원자에게 로그인을 요구하는 것이 실제로는 벽이었다.
--
--   첫 화면은 '회사 = 로그인', '지원자 = 공고 보기'로 나뉜다. 서류합격해서
--   임시 비밀번호를 받은 사람은 '회사' 버튼이 자기 것이 아니라고 여겨 누르지
--   않는다. 그러면 면접방이 만들어져 있어도 들어갈 길이 없다.
--
--   이 앱은 이미 같은 문제를 한 번 풀었다. 지원은 로그인 없이 하고 접수번호로
--   현황을 조회한다. 면접방도 같은 방식으로 연다 — 초대코드로 들어온다.
--
-- 로그인 세션과 같은 표에 두지 않는다. 이것은 계정이 아니라 "이 방 하나에
-- 대한 출입증"이다. 같은 표에 섞으면 어느 코드로 어디까지 할 수 있는지가
-- 흐려지고, 계정 세션에만 걸어 둔 검사가 이쪽에도 걸린 것처럼 보인다.
--
-- 토큰은 해시만 저장한다. 계정 세션과 같은 이유다 — 표가 통째로 유출돼도
-- 남의 방에 들어갈 수는 없어야 한다.
CREATE TABLE room_access_sessions (
  token_hash TEXT PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id),
  -- 누가 들어왔는지는 코드만으로 알 수 없다. 접속 환경이라도 남겨 두어야
  -- 나중에 "언제 누가 열어 봤는가"를 따질 때 볼 것이 있다.
  entered_ip TEXT,
  entered_user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);

CREATE INDEX idx_room_access_room ON room_access_sessions(room_id);
CREATE INDEX idx_room_access_expires ON room_access_sessions(expires_at);

-- 0051_session_auth_method.sql
-- 이 세션이 어떻게 만들어졌는가, 그리고 어느 방까지인가.
--
-- 면접방 입장 코드가 로그인 수단이 되면서 필요해졌다.
--
-- 코드는 회사 담당자도 볼 수 있다(발급 화면·지원서 상세·재발송). 그러면
-- 담당자가 그 코드로 지원자 계정에 로그인해 근로자 서명을 대신 만들 수 있다.
-- 그런데 지금 서명 기록은 그것을 '계정 비밀번호로 확인된 세션'이라고 적는다 --
-- 없는 근거를 있는 것처럼 부르는 것이고, 이 앱이 만들려는 증명서 자체가
-- 거짓이 된다. 0036 이 금지한 바로 그것이다.
--
-- 막지는 않는다(코드로 서명까지 되는 것이 정해진 방향이다). 대신 어떻게
-- 인증했는지를 그대로 남긴다. 감사추적증명서가 그 값을 문장으로 옮기므로,
-- 나중에 다투는 자리에서 '비밀번호로 확인한 서명'과 '코드로 들어와 한 서명'이
-- 구분된다.
--
-- 소급해서 채우지 않는다. 이 컬럼이 생기기 전 세션이 어떻게 만들어졌는지는
-- 아무도 모르고, 모르는 것을 아는 것처럼 적으면 그 기록 전체를 믿을 수 없게
-- 된다. NULL 은 '기록 없음'이고 비밀번호 로그인으로 읽는다.
ALTER TABLE sessions ADD COLUMN auth_method TEXT;

-- 코드로 만든 세션은 그 방에서만 쓴다.
--
-- 코드는 회사가 한 지원자에게 건넨 값이지 계정 비밀번호가 아니다. 그것으로
-- 대시보드와 다른 방까지 열리면, 코드 한 줄이 계정 전체의 열쇠가 된다.
-- 발급된 방 id 를 세션에 박아 두고 그 방 밖에서는 이 세션을 쓰지 않는다.
--
-- 비밀번호 로그인 세션은 NULL 이다 -- 방에 매이지 않는다는 뜻이다.
ALTER TABLE sessions ADD COLUMN scoped_room_id TEXT;

-- 참고: 0050 의 room_access_sessions 는 더 이상 쓰지 않는다.
-- 코드 입장이 별도 출입증이 아니라 계정 로그인으로 바뀌었기 때문이다.
-- 다만 표와 그 안의 행은 지우지 않는다 -- 그 기간에 누가 언제 어느 기기로
-- 방을 열었는지의 유일한 기록이고, 이 저장소는 증거를 지우지 않는다.

-- 0052_message_alerts.sql
-- 새 메시지를 상대에게 알리기 위해 필요한 두 가지.
--
-- 하나. 이 방에서 마지막으로 '새 메시지' 메일을 언제 보냈는가.
--
-- 대화는 한 번에 여러 줄이 오간다. 줄마다 메일을 보내면 지원자의 메일함이
-- 막히고, 그러면 정작 중요한 메일(서류합격, 최종합격)이 그 사이에 묻힌다.
-- 첫 줄에만 보내고 그 뒤 한동안은 조용히 있기 위해 시각을 남긴다.
--
-- 방에 두는 이유는, 조용히 할 대상이 '이 대화'이기 때문이다. 사람에 두면
-- 다른 방의 대화까지 함께 막힌다.
ALTER TABLE interview_rooms ADD COLUMN last_message_email_at TEXT;

-- 둘. 이 사람이 마지막으로 화면을 열어 둔 시각.
--
-- 눈앞에서 대화하는 사람에게 "새 메시지가 도착했습니다" 메일을 보내는 것은
-- 알림이 아니라 방해다. 방금까지 보고 있었으면 보내지 않는다.
--
-- 로그인 시각이 아니라 열람 시각이다. 로그인은 30일 유지되므로 그것으로는
-- 지금 보고 있는지 알 수 없다.
ALTER TABLE users ADD COLUMN last_seen_at TEXT;

-- 0053_push_subscriptions.sql
-- 창을 닫아도 알림이 도착하려면, 어디로 보낼지를 서버가 들고 있어야 한다.
--
-- 브라우저가 알림을 허용하면 "이 기기로 밀어 주세요"라는 주소(endpoint)와
-- 그 기기만 열 수 있는 열쇠 두 개(p256dh, auth)를 준다. 이 세 값이 있어야
-- 브라우저 회사의 서버를 거쳐 그 사람에게 닿는다.
--
-- 열쇠를 저장하지만 이것으로 이 서버가 무엇을 훔쳐볼 수 있는 것은 아니다.
-- 보내는 쪽 열쇠이고, 오히려 이것으로 암호화해야 밀어 주는 서버가 내용을
-- 못 읽는다.
CREATE TABLE IF NOT EXISTS push_subscriptions (
  endpoint TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  -- 어느 기기인지 사람이 알아볼 수 있게. 여러 기기를 쓰면 목록에서 구분된다.
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 한 사람이 회사 PC·집 노트북처럼 여러 기기를 쓴다. 보낼 때 그 사람의 것을
-- 전부 찾아야 하므로 사람으로 찾는 길을 낸다.
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions(user_id);

-- 0054_direct_messages.sql
-- 사람과 사람 사이의 쪽지.
--
-- 면접방 대화와는 다른 것이다. 방 대화는 그 채용 건의 기록이고, 나중에
-- 채용내정이 성립했는지 판정하는 근거로 읽힌다. 여기 오가는 말은 그 판정에
-- 들어가지 않는다 -- 담당자끼리 "이 지원자 어때요" 하고 묻는 자리다.
--
-- 그래서 방 메시지 표에 얹지 않고 따로 둔다. 얹었다면 방 없는 대화를 담기
-- 위해 room_id 를 비워야 하고, 그 순간 채용내정 판정 질의가 전부
-- "room_id IS NOT NULL" 을 붙여야 하는 표가 된다. 하나라도 빠뜨리면 사담이
-- 회사의 채용 확정 발언으로 잡힌다.
CREATE TABLE direct_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id TEXT NOT NULL REFERENCES users(id),
  recipient_id TEXT NOT NULL REFERENCES users(id),
  body TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  -- 읽은 시각. 안 읽었으면 NULL.
  read_at TEXT
);

-- 두 사람 사이의 대화를 시간순으로 읽는다. 보낸 쪽과 받는 쪽이 번갈아
-- 바뀌므로 한 쌍을 정렬한 키(작은 id, 큰 id)로 묶어 둔다.
CREATE INDEX idx_dm_pair ON direct_messages(
  (CASE WHEN sender_id < recipient_id THEN sender_id ELSE recipient_id END),
  (CASE WHEN sender_id < recipient_id THEN recipient_id ELSE sender_id END),
  id
);

-- 안 읽은 것 세기. 화면이 20초마다 두드리는 질의라 색인이 없으면
-- 사람 수만큼 전체 훑기가 된다.
CREATE INDEX idx_dm_inbox ON direct_messages(recipient_id, read_at, id);

-- 0055_contract_archive.sql
-- 체결된 근로계약서의 영구 보관소.
--
-- 지금까지 계약서는 면접방에 매달려 있었다. 방을 지우면 계약 조건도, 서명도,
-- 증명서도, R2 에 올린 PDF 도 함께 사라졌다. 삭제 앞에 "보존 의무가 남아
-- 있습니다" 라는 확인 한 단계가 있었지만, 확인하면 그대로 지워졌다.
--
-- 그런데 근로기준법 제42조와 시행령 제22조 제2항은 근로계약서를 근로관계가
-- 끝난 날부터 3년간 보존하라고 한다. 보존 의무의 대상은 '면접방' 이 아니라
-- '계약서' 다. 방은 대화하던 자리일 뿐이고, 계약서는 그 자리가 없어져도
-- 남아 있어야 하는 것이다.
--
-- 그래서 방과 끊어 낸다.
--
-- room_id 에 외래키를 걸지 않는다. 일부러다. 외래키를 걸면 방을 지울 때
-- 이 표도 함께 지워야 하고(그러면 보관이 아니다), 지우지 않으면 삭제 자체가
-- 실패한다. 어느 쪽도 답이 아니다. room_id 는 "어느 방에서 나온 계약인가" 를
-- 적어 두는 기록일 뿐, 그 방이 살아 있어야 한다는 뜻이 아니다.
--
-- 같은 이유로 사람도 참조하지 않고 이름과 이메일을 그대로 적어 둔다. 계정이
-- 지워져도 "누가 누구와 맺은 계약인가" 는 남아야 한다.
CREATE TABLE contract_archive (
  id TEXT PRIMARY KEY,
  -- 어느 방에서 나왔는가. 외래키가 아니다(위 설명).
  room_id TEXT NOT NULL UNIQUE,
  room_title TEXT,

  -- 당사자. 계정이 사라져도 남는다.
  employer_name TEXT,
  employer_user_id TEXT,
  employee_name TEXT,
  employee_user_id TEXT,
  employee_email TEXT,

  -- 보존 기간을 계산하는 데 필요한 날짜들.
  contract_start_date TEXT,
  contract_end_date TEXT,
  employment_ended_at TEXT,
  signed_at TEXT,
  -- 보존 만료일. 근로관계가 끝난 날부터 3년. 끝나지 않았으면 NULL.
  retention_until TEXT,

  -- 계약 내용 전체와 서명. 다시 만들어 낼 수 있을 만큼 통째로 담는다.
  terms_json TEXT NOT NULL,
  signatures_json TEXT NOT NULL,
  -- 서명 시점에 계산한 계약 내용 지문. 서명 행에 남은 것과 같아야 한다.
  fingerprint TEXT,
  certificate_serial TEXT,

  -- R2 에 저장한 정본. 방을 지워도 이 파일은 지우지 않는다.
  document_key TEXT NOT NULL,
  document_sha256 TEXT NOT NULL,
  document_bytes INTEGER NOT NULL,

  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  -- 원본 면접방이 삭제된 시각. 계약서는 남고 방만 사라졌다는 표시.
  source_deleted_at TEXT
);

CREATE INDEX idx_contract_archive_signed ON contract_archive(signed_at DESC);
CREATE INDEX idx_contract_archive_employee ON contract_archive(employee_user_id);

-- 0056_video_interviews.sql
-- 화상 면접의 업무 기록과 RealtimeKit 식별자를 분리해 보관한다.
-- 참가자 인증 토큰은 짧게 쓰고 버리는 비밀이므로 어느 표에도 저장하지 않는다.

CREATE TABLE interview_sessions (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES interview_rooms(id) ON DELETE CASCADE,
  provider_meeting_id TEXT NOT NULL UNIQUE,
  provider_session_id TEXT,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled','waiting','live','ended','cancelled','failed')),
  recording_required INTEGER NOT NULL DEFAULT 1
    CHECK (recording_required IN (0, 1)),
  scheduled_at TEXT,
  started_at TEXT,
  ended_at TEXT,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  idempotency_key TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (room_id, idempotency_key)
);

CREATE INDEX idx_interview_sessions_room_created
  ON interview_sessions(room_id, created_at DESC);
CREATE INDEX idx_interview_sessions_provider_session
  ON interview_sessions(provider_session_id);
CREATE INDEX idx_interview_sessions_status
  ON interview_sessions(status);
CREATE UNIQUE INDEX idx_interview_sessions_one_active_per_room
  ON interview_sessions(room_id)
  WHERE status IN ('scheduled', 'waiting', 'live');

-- 관리자 삭제/reset과 세션 생성의 경합을 D1에서 직렬화한다. 외부 provider
-- meeting을 만든 요청도 세션 INSERT 시 이 잠금을 다시 확인하며, 잠겼다면
-- provider meeting을 INACTIVE로 보상 정리한다.
CREATE TABLE interview_room_deletion_locks (
  room_id TEXT PRIMARY KEY REFERENCES interview_rooms(id) ON DELETE CASCADE,
  lock_token TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 기존 면접방 채팅은 그대로 한 흐름으로 유지하되, 세션 전용 면접관에게는
-- 자신이 등록된 화상 면접에서 오간 공개 메시지만 보여 줄 수 있어야 한다.
ALTER TABLE chat_messages
  ADD COLUMN interview_session_id TEXT
    REFERENCES interview_sessions(id) ON DELETE SET NULL;

CREATE INDEX idx_chat_messages_interview_session
  ON chat_messages(interview_session_id, id);

CREATE TABLE interview_session_members (
  session_id TEXT NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('host','interviewer','candidate','observer')),
  custom_participant_id TEXT NOT NULL,
  provider_participant_id TEXT,
  provider_peer_id TEXT,
  admitted_at TEXT,
  joined_at TEXT,
  left_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (session_id, user_id),
  UNIQUE (session_id, custom_participant_id),
  UNIQUE (session_id, provider_participant_id)
);

CREATE INDEX idx_interview_members_user
  ON interview_session_members(user_id, session_id);
CREATE INDEX idx_interview_members_custom_id
  ON interview_session_members(custom_participant_id);

CREATE TABLE interview_recording_consents (
  session_id TEXT NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notice_version TEXT NOT NULL,
  notice_hash TEXT NOT NULL,
  granted INTEGER NOT NULL CHECK (granted IN (0, 1)),
  consented_at TEXT,
  revoked_at TEXT,
  ip_address TEXT,
  user_agent TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (session_id, user_id, notice_version)
);

CREATE INDEX idx_interview_consents_current
  ON interview_recording_consents(session_id, notice_version, notice_hash, granted);

CREATE TABLE interview_recordings (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
  provider_recording_id TEXT UNIQUE,
  provider_session_id TEXT,
  status TEXT NOT NULL
    CHECK (status IN ('starting','recording','paused','stopping','processing','available','failed','deleted')),
  r2_key TEXT UNIQUE,
  storage_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (storage_status IN ('pending','copying','stored','copy_failed','deleted')),
  sha256 TEXT,
  size_bytes INTEGER,
  duration_seconds INTEGER,
  content_type TEXT NOT NULL DEFAULT 'video/mp4',
  filename TEXT,
  provider_download_url TEXT,
  provider_download_url_expires_at TEXT,
  retention_until TEXT,
  started_at TEXT,
  stopped_at TEXT,
  failure_reason TEXT,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  deleted_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 공급자 호출이 동시에 두 번 일어나 별도 녹화가 생기지 않게 D1에서도 막는다.
CREATE UNIQUE INDEX idx_interview_recordings_one_active
  ON interview_recordings(session_id)
  WHERE status IN ('starting','recording','paused','stopping','processing');
CREATE INDEX idx_interview_recordings_session_created
  ON interview_recordings(session_id, created_at DESC);
CREATE INDEX idx_interview_recordings_retention
  ON interview_recordings(retention_until)
  WHERE deleted_at IS NULL;

CREATE TABLE interview_events (
  id TEXT PRIMARY KEY,
  session_id TEXT REFERENCES interview_sessions(id) ON DELETE CASCADE,
  provider_event_id TEXT UNIQUE,
  event_type TEXT NOT NULL,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  details_json TEXT,
  occurred_at TEXT,
  received_at TEXT NOT NULL DEFAULT (datetime('now')),
  processing_started_at TEXT,
  processed_at TEXT
);

CREATE INDEX idx_interview_events_session_received
  ON interview_events(session_id, received_at DESC);
CREATE INDEX idx_interview_events_unprocessed
  ON interview_events(processed_at)
  WHERE processed_at IS NULL;

CREATE TABLE recording_access_logs (
  id TEXT PRIMARY KEY,
  recording_id TEXT NOT NULL REFERENCES interview_recordings(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (action IN ('view','download','delete')),
  outcome TEXT NOT NULL CHECK (outcome IN ('allowed','denied','failed')),
  ip_address TEXT,
  user_agent TEXT,
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_recording_access_recording_created
  ON recording_access_logs(recording_id, created_at DESC);
CREATE INDEX idx_recording_access_user_created
  ON recording_access_logs(user_id, created_at DESC);

-- The browser never queries these tables directly. Only the Edge Function's
-- server-side Postgres connection may read or write business data.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_limit_hits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_edit_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.final_offer_emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_postings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.application_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signed_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_change_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signature_revocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_lifecycle_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.negotiation_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_access_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_archive ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_room_deletion_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_session_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_recording_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_recordings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recording_access_logs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES
  ('documents', 'documents', false, 10485760),
  ('interview-recordings', 'interview-recordings', false, 1073741824)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit;

COMMIT;
